server:
  port: 9090
spring:
  application:
    name: apigateway
  zipkin:
    baseUrl: http://zipkin-svc:9411
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
microservice:
  payment: http://payment-service-svc
  inventory: http://inventory-service-svc
  filter: http://filter-service-svc
  invoice: http://invoice-service-svc
