eureka:
  client:
    fetch-registry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://eureka-svc:9001/eureka/
  instance:
    preferIpAddress: true
spring:
 application:
  name: inventory-service
 zipkin:
  baseUrl: http://zipkin-svc:9411
 cloud:
  config:
   profile: dev
 datasource:
  password: root
  url: jdbc:mysql://${DB_HOST:localhost}:3306/inventorydb
  username: admin
 jpa:
   hibernate:
     ddl-auto: update
   properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQLDialect
   show-sql: true 
 kafka:
     consumer:
       auto-offset-reset: earliest
       bootstrap-servers: kafka:9092
       group-id: inventory2
       key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
       properties:
         spring:
           json:
             trusted:
               packages: '*'
       value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
microservice:
  payment: http://payment-service-svc
  inventory: http://inventory-service-svc
  filter: http://filter-service-svc
  invoice: http://invoice-service-svc
  rental: http://rental-service-svc
