server:
  port: 8084
spring:
  application:
    name: rental
  zipkin:
    baseUrl: http://zipkin-svc:9411
  datasource:
    password: root
    url: jdbc:mysql://${DB_HOST:localhost}:3306/rentaldb
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
microservice:
  payment: http://payment-service-svc
  inventory: http://inventory-service-svc
  filter: http://filter-service-svc
  invoice: http://invoice-service-svc
  rental: http://rental-service-svc
